
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Main-Hall
 */
public class AddCategory extends javax.swing.JFrame {

    /**
     * Creates new form AddCategory
     */
    public AddCategory() {
        initComponents();

        setSize(800, 600);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x =  ((d.width) - this.getWidth())/2;
        int y =  ((d.height) - this.getHeight())/2;
        setLocation(x, y);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbcuisine = new javax.swing.JComboBox<>();
        tfcategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfdes = new javax.swing.JTextArea();
        bt = new javax.swing.JButton();
        addcategory = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 200, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cuisine");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 130, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 190, 90, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 260, 130, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Photo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 330, 100, 22);

        cbcuisine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "Chinese", "Italian", "South Indian" }));
        cbcuisine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcuisineActionPerformed(evt);
            }
        });
        getContentPane().add(cbcuisine);
        cbcuisine.setBounds(210, 130, 280, 30);

        tfcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(tfcategory);
        tfcategory.setBounds(210, 180, 280, 30);

        tfdes.setColumns(20);
        tfdes.setRows(5);
        jScrollPane1.setViewportView(tfdes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 230, 360, 80);

        bt.setText("Browse");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(210, 330, 160, 40);

        addcategory.setText("Add category");
        addcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(addcategory);
        addcategory.setBounds(210, 390, 230, 50);
        getContentPane().add(lblphoto);
        lblphoto.setBounds(450, 340, 150, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbcuisineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcuisineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcuisineActionPerformed
    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

  File f;
    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        JFileChooser jfc;
        jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "bmp");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int ans = jfc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            try {
                BufferedImage bi = ImageIO.read(f);
                BufferedImage resizebi = resize(bi, lblphoto.getWidth(),lblphoto.getHeight());
                lblphoto.setIcon(new ImageIcon(resizebi));
            } catch (IOException ex) {
                Logger.getLogger(AddCategory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btActionPerformed

    private void addcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcategoryActionPerformed
        String category = tfcategory.getText();
        String cuisine =  cbcuisine.getSelectedItem().toString();
        String desc = tfdes.getText();
        
        if (category.isEmpty() || cuisine.isEmpty() || desc.isEmpty() || f == null) {
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory");
        } else 
        {
            try {
                HttpResponse<String> res = Unirest.post("http://localhost:8888/AddCategory")
                        .queryString("category",category)
                        .queryString("cuisine",cuisine)
                        .queryString("desc",desc)
                        .field("photo",f).asString();
                String response = res.getBody();
               
                if(response.equals("success"))
                {
                    JOptionPane.showMessageDialog(this, "Category Added");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Duplicate Category Name");
                }
            } catch (UnirestException ex) {
                Logger.getLogger(AddCategory.class.getName()).log(Level.SEVERE, null, ex);
            }
                       
        }

    }//GEN-LAST:event_addcategoryActionPerformed

    private void tfcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcategoryActionPerformed


    }//GEN-LAST:event_tfcategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcategory;
    private javax.swing.JButton bt;
    private javax.swing.JComboBox<String> cbcuisine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JTextField tfcategory;
    private javax.swing.JTextArea tfdes;
    // End of variables declaration//GEN-END:variables
}
