
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.ArrayList;
import java.util.Locale.Category;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Main-Hall
 */
public class addfooditem extends javax.swing.JFrame {

    ArrayList<Category> al = new ArrayList<>();

    /**
     * Creates new form addfooditem
     */
    public addfooditem() {
        initComponents();
        setSize(800, 600);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x =  ((d.width) - this.getWidth())/2;
        int y =  ((d.height) - this.getHeight())/2;
        setLocation(x, y);
          setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbcuisine1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbfoodcategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfitem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbveg = new javax.swing.JRadioButton();
        rbnonveg = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tfprice = new javax.swing.JTextField();
        lbphoto2 = new javax.swing.JLabel();
        btadditem = new javax.swing.JButton();
        btbrowse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadescri = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Food Item");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, -20, 210, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cuisine");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 80, 40);

        cbcuisine1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "Chinese", "Italian", "South Indian" }));
        cbcuisine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcuisine1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbcuisine1);
        cbcuisine1.setBounds(230, 80, 270, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Food Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 120, 50);

        cbfoodcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfoodcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbfoodcategory);
        cbfoodcategory.setBounds(230, 130, 270, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Item Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 180, 120, 40);
        getContentPane().add(tfitem);
        tfitem.setBounds(230, 190, 270, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Food Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 320, 90, 30);

        buttonGroup1.add(rbveg);
        rbveg.setSelected(true);
        rbveg.setText("Veg");
        getContentPane().add(rbveg);
        rbveg.setBounds(240, 330, 43, 23);

        buttonGroup1.add(rbnonveg);
        rbnonveg.setText("Non Veg");
        getContentPane().add(rbnonveg);
        rbnonveg.setBounds(390, 330, 100, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Price");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 370, 37, 22);
        getContentPane().add(tfprice);
        tfprice.setBounds(230, 370, 270, 30);
        getContentPane().add(lbphoto2);
        lbphoto2.setBounds(520, 320, 150, 140);

        btadditem.setText("Add Items");
        btadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadditemActionPerformed(evt);
            }
        });
        getContentPane().add(btadditem);
        btadditem.setBounds(230, 420, 270, 40);

        btbrowse.setText("Browse");
        btbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btbrowse);
        btbrowse.setBounds(530, 240, 130, 40);

        tadescri.setColumns(20);
        tadescri.setRows(5);
        jScrollPane1.setViewportView(tadescri);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 230, 270, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbfoodcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfoodcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfoodcategoryActionPerformed
    BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    File f;
    private void btbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbrowseActionPerformed
        // TODO add your handling code here: JFileChooser jfc;
        JFileChooser jfc;
        jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "bmp");
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        int ans = jfc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            try {
                BufferedImage bi = ImageIO.read(f);
                BufferedImage resizebi = resize(bi, lbphoto2.getWidth(), lbphoto2.getHeight());
                lbphoto2.setIcon(new ImageIcon(resizebi));
            } catch (IOException ex) {
                Logger.getLogger(AddCategory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btbrowseActionPerformed

    private void cbcuisine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcuisine1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String cuisine = cbcuisine1.getSelectedItem().toString();
            HttpResponse<String> res = Unirest.get("http://localhost:8888/getcategorynamebycuisine")
                    .queryString("cuisine", cuisine).asString();
            String response = res.getBody();
            StringTokenizer st = new StringTokenizer(response, "#$%");
            int n = st.countTokens();
            cbfoodcategory.removeAllItems();
            for (int i = 1; i <= n; i++) {
                String catname = st.nextToken();
                cbfoodcategory.addItem(catname);
            }

        } catch (UnirestException ex) {
            Logger.getLogger(viewcategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbcuisine1ActionPerformed

    private void btadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadditemActionPerformed
        // TODO add your handling code here:

        String type = rbveg.isSelected() ? "Veg" : "Non-Veg";

        String category = cbfoodcategory.getSelectedItem().toString();
        String desc = tadescri.getText();
        String itemname = tfitem.getText();
        String price = tfprice.getText();

        if (category.isEmpty() || desc.isEmpty() || itemname.isEmpty() || price.isEmpty() || f == null) {
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory");
        } else {
            try {
                HttpResponse<String> res = Unirest.post("http://localhost:8888/Addfooditem")
                        .queryString("category", category)
                        .queryString("itemname", itemname)
                        .queryString("price", price)
                        .queryString("description", desc)
                        .queryString("type", type)
                        .field("photo", f).asString();
                String response = res.getBody();

                if (response.equals("success")) {
                    JOptionPane.showMessageDialog(this, "Category Added");
                } else {
                    JOptionPane.showMessageDialog(this, "Duplicate Category Name");
                }
            } catch (UnirestException ex) {
                Logger.getLogger(AddCategory.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_btadditemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addfooditem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadditem;
    private javax.swing.JButton btbrowse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbcuisine1;
    private javax.swing.JComboBox<String> cbfoodcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbphoto2;
    private javax.swing.JRadioButton rbnonveg;
    private javax.swing.JRadioButton rbveg;
    private javax.swing.JTextArea tadescri;
    private javax.swing.JTextField tfitem;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables
}
