
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import jdk.nashorn.internal.runtime.regexp.joni.EncodingHelper;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Main-Hall
 */
public class AdminChangePassword extends javax.swing.JFrame {

    String uname;
    /**
     * Creates new form AdminChangePassword
     */
    public AdminChangePassword() {
        initComponents();
      
       
    }
  public AdminChangePassword(String username) {
      uname= username;
        initComponents();
        
      
        lbusername.setText(uname);
          setSize(800, 600);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x =  ((d.width) - this.getWidth())/2;
        int y =  ((d.height) - this.getHeight())/2;
        setLocation(x, y);
         setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pfoldpass = new javax.swing.JPasswordField();
        pfnewpass = new javax.swing.JPasswordField();
        pfconfpass = new javax.swing.JPasswordField();
        bt5 = new javax.swing.JButton();
        lbusername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Admin Change Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 110, 100, 20);

        jLabel3.setText("Old Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 65, 14);

        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 210, 70, 14);

        jLabel5.setText("Confirm Pasword");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 260, 130, 14);
        getContentPane().add(pfoldpass);
        pfoldpass.setBounds(240, 160, 230, 30);
        getContentPane().add(pfnewpass);
        pfnewpass.setBounds(240, 200, 230, 30);
        getContentPane().add(pfconfpass);
        pfconfpass.setBounds(240, 250, 230, 30);

        bt5.setText("Change Password");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5);
        bt5.setBounds(270, 300, 160, 30);
        getContentPane().add(lbusername);
        lbusername.setBounds(240, 110, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        String oldpass = pfoldpass.getText();
        String newpass = pfnewpass.getText();
        String confpass = pfconfpass.getText();
        if(oldpass.equals("") || newpass.equals("") || confpass.equals(""))
        {
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory");
        }
        else if(newpass.equals(confpass) == false)
        {
            JOptionPane.showMessageDialog(this, "New Password and Confirm Password Must Be Same");
        }
        else
        {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8888/adminchangepassword")
                        .queryString("username",uname)
                        .queryString("oldpass",oldpass)
                        .queryString("newpass",newpass).asString();
                 String response = res.getBody();
                 if(response.equals("success"))
                     JOptionPane.showMessageDialog(this, "Password changed");
                 else
                     JOptionPane.showMessageDialog(this, "Invalid Old Password");
            } catch (UnirestException ex) {
                Logger.getLogger(AdminChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_bt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbusername;
    private javax.swing.JPasswordField pfconfpass;
    private javax.swing.JPasswordField pfnewpass;
    private javax.swing.JPasswordField pfoldpass;
    // End of variables declaration//GEN-END:variables
}
