
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Main-Hall
 */
public class editfooditem extends javax.swing.JFrame {

    /**
     * Creates new form editfooditem
     */
    public editfooditem() {
        initComponents();
      
        
    }
    String category, itemname, desc, price, type;

    editfooditem(String category, String itemname, String desc, String price, String type) {
        initComponents();
        setSize(800, 600);
         Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x =  ((d.width) - this.getWidth())/2;
        int y =  ((d.height) - this.getHeight())/2;
        setLocation(x, y);
        setVisible(true);
        this.category = category;
        this.itemname = itemname;
        this.desc = desc;
        this.price = price;
        this.type = type;
        if (type.equals("Veg")) {
            rbveg.setSelected(true);
        } else {
            rbnonveg.setSelected(true);
        }
        tfcategory.setText(category);
        tfitemname.setText(itemname);
        tadescrib.setText(desc);
        tfprice.setText(price);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadescrib = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tfprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbveg = new javax.swing.JRadioButton();
        rbnonveg = new javax.swing.JRadioButton();
        btupdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfitemname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfcategory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Update Food Item");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 210, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Description");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 220, 90, 30);

        tadescrib.setColumns(20);
        tadescrib.setRows(5);
        jScrollPane1.setViewportView(tadescrib);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 190, 310, 90);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 320, 90, 30);

        tfprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpriceActionPerformed(evt);
            }
        });
        getContentPane().add(tfprice);
        tfprice.setBounds(230, 310, 310, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 370, 90, 30);

        buttonGroup1.add(rbveg);
        rbveg.setSelected(true);
        rbveg.setText("Veg");
        rbveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbvegActionPerformed(evt);
            }
        });
        getContentPane().add(rbveg);
        rbveg.setBounds(260, 370, 43, 23);

        buttonGroup1.add(rbnonveg);
        rbnonveg.setText("Non-Veg");
        getContentPane().add(rbnonveg);
        rbnonveg.setBounds(390, 360, 140, 40);

        btupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btupdate.setText("Update");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btupdate);
        btupdate.setBounds(220, 420, 230, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Item Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 140, 110, 30);

        tfitemname.setEnabled(false);
        tfitemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfitemnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfitemname);
        tfitemname.setBounds(230, 140, 300, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Category Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 90, 130, 30);

        tfcategory.setEnabled(false);
        tfcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(tfcategory);
        tfcategory.setBounds(230, 90, 300, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpriceActionPerformed

    private void rbvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbvegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbvegActionPerformed
  
   
    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        String itemname =tfitemname.getText();
        String description = tadescrib.getText();
        int price = Integer.parseInt(tfprice.getText());
        String type = rbveg.isSelected() ? "Veg" : "Non-Veg";
        
        if (itemname.isEmpty() || description.isEmpty() || tfprice.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory");
        } else {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8888/editfooditem")
                        .queryString("category", category)
                        .queryString("itemname", itemname)
                        .queryString("description", description)
                        .queryString("type", type)
                        .queryString("price", price).asString();
                String response = res.getBody();
                if (response.equals("success")) {
                    JOptionPane.showMessageDialog(this, "Data Updated");
                } else {
                    JOptionPane.showMessageDialog(this, "Not Updated");
                }
            } catch (UnirestException ex) {
                Logger.getLogger(AdminChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btupdateActionPerformed

    private void tfitemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfitemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfitemnameActionPerformed

    private void tfcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editfooditem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbnonveg;
    private javax.swing.JRadioButton rbveg;
    private javax.swing.JTextArea tadescrib;
    private javax.swing.JTextField tfcategory;
    private javax.swing.JTextField tfitemname;
    private javax.swing.JTextField tfprice;
    // End of variables declaration//GEN-END:variables
}
