/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Main-Hall
 */
public class FoodItemPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form CategoryPanel
     */
    public FoodItemPanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcatphoto = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lbltype = new javax.swing.JLabel();
        lblitemname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        lbcatphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/1562758569940.jpg"))); // NOI18N
        lbcatphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbcatphoto);
        lbcatphoto.setBounds(10, 40, 210, 130);

        lblprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblprice.setForeground(new java.awt.Color(255, 255, 255));
        lblprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprice.setText("jLabel1");
        add(lblprice);
        lblprice.setBounds(10, 170, 100, 40);

        lbltype.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbltype.setText("jLabel1");
        add(lbltype);
        lbltype.setBounds(150, 180, 70, 30);

        lblitemname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblitemname.setForeground(new java.awt.Color(255, 255, 255));
        lblitemname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblitemname.setText("jLabel1");
        add(lblitemname);
        lblitemname.setBounds(0, 0, 230, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbcatphoto;
    public javax.swing.JLabel lblitemname;
    public javax.swing.JLabel lblprice;
    public javax.swing.JLabel lbltype;
    // End of variables declaration//GEN-END:variables
}
