import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class generatebill extends javax.swing.JFrame {

    /**
     * Creates new form generatebill
     */
    public generatebill() {
        initComponents();
        setSize(600, 600);
        setVisible(true);
        success();
    }

    void success() {
        try {
            System.out.println("success called");
            String billdate = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
            String billtime = new SimpleDateFormat("HH:mm").format(new Date());
            HttpResponse<String> res = Unirest.get("http://localhost:8888/insertbill")
                    .queryString("billdate", billdate)
                    .queryString("billtime", billtime)
                    .queryString("amount", Global.billamount)
                    .queryString("tax", Global.tax)
                    .queryString("paybleamount", Global.paybleamount)
                    .queryString("mobileno", Global.mobileno)
                    .queryString("status", "pending").asString();

            String response = res.getBody();
            if (response.equals("failed") == false) {
                String billid = response;

                for (foodcart fc : Global.al1) {
                    foodcart obj = fc;

                    HttpResponse<String> res2 = Unirest.get("http://localhost:8888/billdetailinsert")
                            .queryString("billid", billid)
                            .queryString("itemname", obj.itemname)
                            .queryString("price", obj.price)
                            .queryString("qty", obj.quantity)
                            .queryString("totalprice", obj.totalprice).asString();
                }
                lblmessage.setText("Order Placed Successfully!!!");
                String smstext = "Your Order having billamount " + Global.paybleamount + " is placed successfully!!!. You will be notified the status of order";
                sendsms.send(Global.mobileno, smstext);
            }

        } catch (UnirestException ex) {
            Logger.getLogger(generatebill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblmessage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generatebill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generatebill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblmessage;
    // End of variables declaration//GEN-END:variables
}
