
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Main-Hall
 */
public class signup2 extends javax.swing.JFrame {

    String mobileno;

    /**
     * Creates new form signup2
     */
    public signup2() {
        initComponents();

    }

    public signup2(String moblienumber) {
        initComponents();
        setSize(800, 600);
        mobileno = moblienumber;
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x = ((d.width) - this.getWidth()) / 2;
        int y = ((d.height) - this.getHeight()) / 2;
        setLocation(x, y);
        setVisible(true);
        tfmob.setText(mobileno);
    }
    boolean flag = false;

    void loaduserinfo(String mobile) {
        try {
            // TODO add your handling code here:
            String mobilenumber = tfmob.getText();
            HttpResponse<String> res = Unirest.get("http://localhost:8888/getsignup2")
                    .queryString("mobilenumber", mobilenumber).asString();
            String response = res.getBody();
            System.out.println("body  " + response);
            if (response.equals("failed") == false) {
                flag = true;
                StringTokenizer st2 = new StringTokenizer(response, "#$%");
                String name = st2.nextToken();
                String email = st2.nextToken();
                String address = st2.nextToken();
                tfname1.setText(name);
                tfemail.setText(email);
                tfaddre.setText(address);
            }

        } catch (UnirestException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfmob = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfname1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        tfaddre = new javax.swing.JTextField();
        btsubmit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mobile No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 70, 120, 60);
        getContentPane().add(tfmob);
        tfmob.setBounds(270, 80, 310, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 170, 90, 30);
        getContentPane().add(tfname1);
        tfname1.setBounds(270, 170, 310, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 260, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 330, 80, 40);
        getContentPane().add(tfemail);
        tfemail.setBounds(270, 250, 310, 40);
        getContentPane().add(tfaddre);
        tfaddre.setBounds(270, 330, 310, 40);

        btsubmit1.setText("Submit");
        btsubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubmit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btsubmit1);
        btsubmit1.setBounds(433, 400, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubmit1ActionPerformed
        // TODO add your handling code here:
        String mobilenumber = tfmob.getText();
        String name = tfname1.getText();
        String address = tfaddre.getText();
        String email = tfemail.getText();

        if (name.isEmpty() || address.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory");
        } else {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8888/signup2")
                        .queryString("mobilenumber", mobilenumber)
                        .queryString("name", name)
                        .queryString("email", email)
                        .queryString("flag", flag)
                        .queryString("address", address).asString();

                String response = res.getBody();

                if (response.equals("success")) {
                    JOptionPane.showMessageDialog(this, "Signup Successfully!!!");
                    Global.mobileno = mobilenumber;
                    customerhome obj = new customerhome();

                } else {
                    JOptionPane.showMessageDialog(this, "Signup failed");
                }
            } catch (UnirestException ex) {
                Logger.getLogger(AddCategory.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btsubmit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsubmit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfaddre;
    private javax.swing.JTextField tfemail;
    private javax.swing.JLabel tfmob;
    private javax.swing.JTextField tfname1;
    // End of variables declaration//GEN-END:variables
}
