
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Main-Hall
 */
public class viewfooditem extends javax.swing.JFrame {

    ArrayList<fooditem> al = new ArrayList<>();
    fooditemTableModel ftm = new fooditemTableModel();
    String iname;
  

    /**
     * Creates new form viewfooditem
     */
    public viewfooditem() {
        initComponents();
        setSize(800, 600);
      jTable1.setModel(ftm);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x =  ((d.width) - this.getWidth())/2;
        int y =  ((d.height) - this.getHeight())/2;
        setLocation(x, y);
        setVisible(true);
    }

    void loaddata() {
        try {
            // TODO add your handling code here:
            String category = cbfoodcategory.getSelectedItem().toString();
            HttpResponse<String> res = Unirest.get("http://localhost:8888/getfooditems")
                    .queryString("category", category).asString();
            String response = res.getBody();
            StringTokenizer st = new StringTokenizer(response, "~!@");
            int n = st.countTokens();
            al.clear();
            for (int i = 1; i <= n; i++) {
                String row = st.nextToken();
                StringTokenizer st2 = new StringTokenizer(row, "#$%");
                String itemname = st2.nextToken();
                String desc = st2.nextToken();
                String type = st2.nextToken();
                String price = st2.nextToken();
                String photo = st2.nextToken();
                fooditem obj = new fooditem(itemname, desc, type, price, photo);
                al.add(obj);
            }
            jTable1.setRowHeight(100);
            jTable1.setShowGrid(true);
            jTable1.getColumnModel().getColumn(4).setCellRenderer(new ImageRenderer());

        } catch (UnirestException ex) {
            Logger.getLogger(viewcategory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbcuisine1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbfoodcategory = new javax.swing.JComboBox<>();
        btview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btdelete1 = new javax.swing.JButton();
        btedit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Food Items");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 250, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select Cuisine");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 60, 110, 50);

        cbcuisine1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "Chinese", "Italian", "South Indian" }));
        cbcuisine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcuisine1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbcuisine1);
        cbcuisine1.setBounds(290, 70, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 110, 140, 60);

        cbfoodcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfoodcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbfoodcategory);
        cbfoodcategory.setBounds(290, 130, 260, 30);

        btview.setText("View");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });
        getContentPane().add(btview);
        btview.setBounds(290, 180, 140, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Description", "Type", "Price", "Photo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 630, 140);

        btdelete1.setText("Delete");
        btdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete1);
        btdelete1.setBounds(150, 410, 130, 30);

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        getContentPane().add(btedit);
        btedit.setBounds(390, 410, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbcuisine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcuisine1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String cuisine = cbcuisine1.getSelectedItem().toString();
            HttpResponse<String> res = Unirest.get("http://localhost:8888/getcategorynamebycuisine")
                    .queryString("cuisine", cuisine).asString();
            String response = res.getBody();
            StringTokenizer st = new StringTokenizer(response, "#$%");
            int n = st.countTokens();
            cbfoodcategory.removeAllItems();
            for (int i = 1; i <= n; i++) {
                String catname = st.nextToken();
                cbfoodcategory.addItem(catname);
            }

        } catch (UnirestException ex) {
            Logger.getLogger(viewcategory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cbcuisine1ActionPerformed

    private void cbfoodcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfoodcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfoodcategoryActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        // TODO add your handling code here:
        loaddata();

    }//GEN-LAST:event_btviewActionPerformed
    BufferedImage resizephoto(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    private void btdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelete1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int index = jTable1.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Please select a category first");
            } else {
                int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Are you sure?", "Delete Confirmation", JOptionPane.OK_CANCEL_OPTION);
                if (showConfirmDialog == JOptionPane.OK_OPTION) {
                    String category = cbfoodcategory.getSelectedItem().toString();
                    String itemname = al.get(index).itemname;
                    HttpResponse<String> res = Unirest.get("http://localhost:8888/deletefooditem")
                            .queryString("category", category)
                            .queryString("itemname",itemname).asString();
                    String response = res.getBody();
                    if (response.equals("success")) {
                        JOptionPane.showMessageDialog(rootPane, "fooditem Deleted");
                        loaddata();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Deletion Failed!!!");
                    }
                }
            }
        } catch (UnirestException ex) {
            Logger.getLogger(viewcategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btdelete1ActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed

               int index = jTable1.getSelectedRow();
            String category =  cbfoodcategory.getSelectedItem().toString();
            String itemname =  al.get(index).itemname;
            String desc =  al.get(index).description;
            String price =  al.get(index).price;
            String type =  al.get(index).type;
            editfooditem obj = new editfooditem(category,itemname,desc,price,type);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewfooditem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewfooditem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdelete1;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btview;
    private javax.swing.JComboBox<String> cbcuisine1;
    private javax.swing.JComboBox<String> cbfoodcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
class fooditem {

        String itemname, description, type, price, photo;

        public fooditem(String itemname, String description, String type, String price, String photo) {
            this.itemname = itemname;
            this.description = description;
            this.type = type;
            this.price = price;
            this.photo = photo;
        }

    }

    class fooditemTableModel extends AbstractTableModel {

        String[] columns = {"itemname", "description", "type", "price", "photo"};

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return al.get(rowIndex).itemname;
                case 1:
                    return al.get(rowIndex).description;
                case 2:
                    return al.get(rowIndex).type;
                case 3:
                    return al.get(rowIndex).price;
                case 4:
                    return al.get(rowIndex).photo;
                default:
                    return null;
            }
        }

        @Override
        public String getColumnName(int column) {
          return  columns[column];
        }
        
        

    }

    class ImageRenderer extends DefaultTableCellRenderer {

        JLabel lbl = new JLabel();
        ImageIcon icon = new ImageIcon("");
        BufferedImage bufferedImage, newimage;

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {
            try {
                URL url = new URL("http://localhost:8888/GetResource/" + al.get(row).photo);
                bufferedImage = ImageIO.read(url);
                newimage = resizephoto(bufferedImage, 100, 100);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            icon = new ImageIcon(newimage);
            lbl.setIcon(icon);
            lbl.setBounds(0, 0, 100, 100);
            return lbl;
        }
    }

}
